import 'dart:developer' as developer;
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';
import 'package:screenshot/screenshot.dart';
import 'package:path_provider/path_provider.dart';
import '../models/meal_plan.dart';
import '../utils/pdf_service.dart';

class MealPlanTable extends StatelessWidget {
  final MealPlan mealPlan;
  final String? modelName;
  final ScreenshotController _screenshotController = ScreenshotController();

  MealPlanTable({super.key, required this.mealPlan, this.modelName});

  Future<void> _sharePlanImage(BuildContext context) async {
    try {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Generating high-res image...'),
          duration: Duration(seconds: 1),
        ),
      );

      // Use a much larger width for export to prevent overlapping
      final double exportWidth = 1200.0;

      final imageBytes = await _screenshotController.captureFromWidget(
        Material(
          color: Colors.white,
          child: Container(
            width: exportWidth,
            padding: const EdgeInsets.all(40),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                _buildMainContent(context, isExport: true),
                const SizedBox(height: 20),
                // Metadata Footer
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Text(
                      "Generated by HealthBuddy",
                      style: TextStyle(
                        color: Colors.grey,
                        fontSize: 14,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    Text(
                      "Model: ${modelName ?? 'NutriGPT'}",
                      style: const TextStyle(color: Colors.grey, fontSize: 14),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
        delay: const Duration(milliseconds: 500),
        pixelRatio: 2.0, // Higher resolution
      );

      final directory = await getApplicationDocumentsDirectory();
      final fileName = 'meal_plan_${DateTime.now().millisecondsSinceEpoch}.png';
      final imagePath = '${directory.path}/$fileName';

      final file = File(imagePath);
      await file.writeAsBytes(imageBytes);

      if (await file.exists()) {
        await Share.shareXFiles([
          XFile(imagePath),
        ], text: 'Check out my ${mealPlan.title}!');
      }
    } catch (e) {
      developer.log("Error in _sharePlanImage: $e");
      if (context.mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  Widget _buildMainContent(BuildContext context, {bool isExport = false}) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: isExport ? Border.all(color: Colors.grey[300]!) : null,
        boxShadow: isExport
            ? []
            : [
                BoxShadow(
                  color: Colors.black.withValues(alpha: 0.08),
                  blurRadius: 15,
                  offset: const Offset(0, 5),
                ),
              ],
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [Colors.purple[700]!, Colors.purple[500]!],
                begin: Alignment.centerLeft,
                end: Alignment.centerRight,
              ),
              borderRadius: const BorderRadius.vertical(
                top: Radius.circular(20),
              ),
            ),
            child: Row(
              children: [
                Expanded(
                  child: Text(
                    mealPlan.title,
                    style: const TextStyle(
                      color: Colors.white,
                      fontWeight: FontWeight.bold,
                      fontSize: 18,
                    ),
                  ),
                ),
              ],
            ),
          ),

          // Use a custom Table widget for more control over wrapping
          isExport
              ? _buildExportTable()
              : SingleChildScrollView(
                  scrollDirection: Axis.horizontal,
                  child: _buildDataTable(),
                ),

          // Note
          if (mealPlan.note != null)
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: Colors.amber[50],
                borderRadius: const BorderRadius.vertical(
                  bottom: Radius.circular(20),
                ),
              ),
              child: Row(
                children: [
                  const Icon(Icons.info_outline, size: 16, color: Colors.amber),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      mealPlan.note!,
                      style: TextStyle(
                        fontSize: 12,
                        color: Colors.grey[700],
                        fontStyle: FontStyle.italic,
                      ),
                    ),
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildDataTable() {
    return DataTable(
      headingRowColor: WidgetStateProperty.all(Colors.purple[50]),
      columnSpacing: 12,
      horizontalMargin: 12,
      columns: _buildColumns(),
      rows: _buildRows(),
    );
  }

  // A fixed-layout table for export to ensure no overlapping
  Widget _buildExportTable() {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Table(
        border: TableBorder.all(color: Colors.grey[200]!),
        columnWidths: const {0: FixedColumnWidth(120)},
        defaultVerticalAlignment: TableCellVerticalAlignment.middle,
        children: [
          // Header Row
          TableRow(
            decoration: BoxDecoration(color: Colors.purple[50]),
            children: [
              _buildExportCell("Meal", isHeader: true),
              ...mealPlan.days.map(
                (d) => _buildExportCell(d.day, isHeader: true),
              ),
            ],
          ),
          // Data Rows
          _buildExportRow(
            '🍳 Breakfast',
            mealPlan.days.map((d) => d.breakfast).toList(),
            Colors.orange[50]!,
          ),
          _buildExportRow(
            '🥜 Snack',
            mealPlan.days.map((d) => d.snack1).toList(),
            Colors.red[50]!,
          ),
          _buildExportRow(
            '🍱 Lunch',
            mealPlan.days.map((d) => d.lunch).toList(),
            Colors.green[50]!,
          ),
          _buildExportRow(
            '🍎 Snack',
            mealPlan.days.map((d) => d.snack2).toList(),
            Colors.amber[50]!,
          ),
          _buildExportRow(
            '🍽️ Dinner',
            mealPlan.days.map((d) => d.dinner).toList(),
            Colors.blue[50]!,
          ),
          if (mealPlan.days.any((d) => d.beverages != null))
            _buildExportRow(
              '🥤 Beverages',
              mealPlan.days.map((d) => d.beverages).toList(),
              Colors.teal[50]!,
            ),
        ],
      ),
    );
  }

  TableRow _buildExportRow(String label, List<String?> meals, Color color) {
    return TableRow(
      decoration: BoxDecoration(color: color),
      children: [
        _buildExportCell(label, fontWeight: FontWeight.bold),
        ...meals.map((m) => _buildExportCell(m ?? "-")),
      ],
    );
  }

  Widget _buildExportCell(
    String text, {
    bool isHeader = false,
    FontWeight? fontWeight,
  }) {
    return Padding(
      padding: const EdgeInsets.all(12.0),
      child: Text(
        text,
        style: TextStyle(
          fontWeight: isHeader ? FontWeight.bold : fontWeight,
          fontSize: isHeader ? 14 : 12,
          color: isHeader ? Colors.purple : Colors.black87,
        ),
        softWrap: true,
      ),
    );
  }

  List<DataColumn> _buildColumns() {
    return [
      const DataColumn(
        label: Text(
          'Meal',
          style: TextStyle(fontWeight: FontWeight.bold, color: Colors.purple),
        ),
      ),
      ...mealPlan.days.map(
        (d) => DataColumn(
          label: Text(
            d.day,
            style: TextStyle(
              fontWeight: FontWeight.bold,
              color: Colors.purple[700],
            ),
          ),
        ),
      ),
    ];
  }

  List<DataRow> _buildRows() {
    return [
      _buildMealRow(
        '🍳 Breakfast',
        mealPlan.days.map((d) => d.breakfast).toList(),
        Colors.orange[50]!,
      ),
      _buildMealRow(
        '🥜 Snack',
        mealPlan.days.map((d) => d.snack1).toList(),
        Colors.red[50]!,
      ),
      _buildMealRow(
        '🍱 Lunch',
        mealPlan.days.map((d) => d.lunch).toList(),
        Colors.green[50]!,
      ),
      _buildMealRow(
        '🍎 Snack',
        mealPlan.days.map((d) => d.snack2).toList(),
        Colors.amber[50]!,
      ),
      _buildMealRow(
        '🍽️ Dinner',
        mealPlan.days.map((d) => d.dinner).toList(),
        Colors.blue[50]!,
      ),
      if (mealPlan.days.any((d) => d.beverages != null))
        _buildMealRow(
          '🥤 Beverages',
          mealPlan.days.map((d) => d.beverages).toList(),
          Colors.teal[50]!,
        ),
    ];
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(vertical: 8),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 4, vertical: 4),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Text(
                  "Weekly Plan",
                  style: TextStyle(
                    color: Colors.grey,
                    fontSize: 12,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                Row(
                  children: [
                    InkWell(
                      onTap: () => PdfService.generateMealPlanPdf(
                        mealPlan,
                        modelName ?? "NutriGPT",
                      ),
                      child: Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 12,
                          vertical: 6,
                        ),
                        decoration: BoxDecoration(
                          color: Colors.red[50],
                          borderRadius: BorderRadius.circular(20),
                          border: Border.all(
                            color: Colors.red.withValues(alpha: 0.3),
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Icon(
                              Icons.picture_as_pdf,
                              size: 14,
                              color: Colors.red[700],
                            ),
                            const SizedBox(width: 4),
                            Text(
                              "Export PDF",
                              style: TextStyle(
                                fontSize: 12,
                                fontWeight: FontWeight.bold,
                                color: Colors.red[700],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(width: 8),
                    InkWell(
                      onTap: () => _sharePlanImage(context),
                      child: Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 12,
                          vertical: 6,
                        ),
                        decoration: BoxDecoration(
                          color: Colors.purple[50],
                          borderRadius: BorderRadius.circular(20),
                          border: Border.all(
                            color: Colors.purple.withValues(alpha: 0.3),
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Icon(
                              Icons.share,
                              size: 14,
                              color: Colors.purple[700],
                            ),
                            const SizedBox(width: 4),
                            Text(
                              "Export Image",
                              style: TextStyle(
                                fontSize: 12,
                                fontWeight: FontWeight.bold,
                                color: Colors.purple[700],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
          _buildMainContent(context),
        ],
      ),
    );
  }

  DataRow _buildMealRow(String mealType, List<String?> meals, Color rowColor) {
    return DataRow(
      color: WidgetStateProperty.all(rowColor),
      cells: [
        DataCell(
          Text(
            mealType,
            style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 13),
          ),
        ),
        ...meals.map(
          (meal) => DataCell(
            Container(
              constraints: const BoxConstraints(maxWidth: 120),
              child: Text(
                meal ?? '-',
                style: const TextStyle(fontSize: 12),
                softWrap: true,
              ),
            ),
          ),
        ),
      ],
    );
  }
}
